version: '3'
services:
  composer:
    image: composer:2.4.2
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  php:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
